# Generated by Django 5.2 on 2025-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_usuario', '0002_remove_infousuario_img_perfil_infousuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infousuario',
            name='avatar',
        ),
        migrations.AddField(
            model_name='infousuario',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil'),
        ),
    ]
