# Generated by Django 5.2 on 2025-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_usuario', '0003_remove_infousuario_avatar_infousuario_img_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='img_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img_perfil/'),
        ),
    ]
