# Generated by Django 5.2 on 2025-04-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_usuario', '0005_remove_infousuario_img_perfil_infousuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
