# Generated by Django 5.2 on 2025-04-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_usuario', '0006_alter_infousuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infousuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
