# Generated by Django 5.2 on 2025-04-28 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_usuario', '0007_alter_infousuario_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoUsuario',
            new_name='InfoExtra',
        ),
    ]
