# Generated by Django 5.2 on 2025-04-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_usuario', '0008_rename_infousuario_infoextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='infoextra',
            name='date_joined',
            field=models.DateField(null=True),
        ),
    ]
