# Generated by Django 5.2 on 2025-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remera',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
