# Generated by Django 5.2 on 2025-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_app', '0002_remera_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='artista',
            field=models.CharField(max_length=100, verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='year',
            field=models.IntegerField(verbose_name='Año de Lanzamiento'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='color',
            field=models.CharField(default='', max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='disenio',
            field=models.CharField(max_length=100, verbose_name='Diseño'),
        ),
        migrations.AlterField(
            model_name='remera',
            name='talle',
            field=models.CharField(max_length=6, verbose_name='Talle'),
        ),
    ]
