# Generated by Django 5.2 on 2025-05-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_app', '0003_alter_disco_artista_alter_disco_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
